[project]
name = "eduvisor"
version = "0.1.0"
description = "Eduvisor integration for OneMDP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["ruff>=0.12.0"]
