name: Trigger auto deployment for eduvisor-prod-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/eduvisor-prod-1-AutoDeployTrigger-872681f6-00c8-425f-a3b6-4343726e1b7a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EDUVISORPROD1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EDUVISORPROD1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EDUVISORPROD1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: onemdpregistry.azurecr.io
          registryUsername: ${{ secrets.EDUVISORPROD1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EDUVISORPROD1_REGISTRY_PASSWORD }}
          containerAppName: eduvisor-prod-1
          resourceGroup: onemdp-resource-group
          imageToBuild: onemdpregistry.azurecr.io/eduvisor-prod-1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


